"""init_star_schema_and_bronze_layer

Revision ID: aa06b110cd92
Revises: 
Create Date: 2026-05-02 12:09:42.674429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa06b110cd92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bronze_raw_scrape',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_competitors',
    sa.Column('competitor_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competitor_id_ext', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('competitor_key'),
    sa.UniqueConstraint('competitor_id_ext')
    )
    op.create_table('dim_products',
    sa.Column('product_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id_ext', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('product_key'),
    sa.UniqueConstraint('product_id_ext')
    )
    op.create_table('dim_time',
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('date_key'),
    sa.UniqueConstraint('full_date')
    )
    op.create_table('fact_market_trends',
    sa.Column('trend_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_key', sa.Integer(), nullable=False),
    sa.Column('competitor_key', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('review_volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_key'], ['dim_competitors.competitor_key'], ),
    sa.ForeignKeyConstraint(['date_key'], ['dim_time.date_key'], ),
    sa.ForeignKeyConstraint(['product_key'], ['dim_products.product_key'], ),
    sa.PrimaryKeyConstraint('trend_id')
    )
    op.create_index('idx_fact_competitor_price', 'fact_market_trends', ['competitor_key', 'price'], unique=False)
    op.create_index('idx_fact_date_product', 'fact_market_trends', ['date_key', 'product_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fact_date_product', table_name='fact_market_trends')
    op.drop_index('idx_fact_competitor_price', table_name='fact_market_trends')
    op.drop_table('fact_market_trends')
    op.drop_table('dim_time')
    op.drop_table('dim_products')
    op.drop_table('dim_competitors')
    op.drop_table('bronze_raw_scrape')
    # ### end Alembic commands ###
